[package]
edition = "2018"
name = "ra_hir"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[dependencies]
arrayvec = "0.4.10"
log = "0.4.5"
relative-path = "0.4.0"
rustc-hash = "1.0"
parking_lot = "0.7.0"
ena = "0.11"
join_to_string = "0.1.3"

ra_syntax = { path = "../ra_syntax" }
ra_arena = { path = "../ra_arena" }
ra_db = { path = "../ra_db" }
mbe = { path = "../ra_mbe", package = "ra_mbe" }
tt = { path = "../ra_tt", package = "ra_tt" }
test_utils = { path = "../test_utils" }
ra_prof = {path = "../ra_prof" }

lang_api = { path = "../lang_api" }

[dev-dependencies]
flexi_logger = "0.11.0"
insta = "0.7.0"
